language: c

sudo: true
dist:  bionic

addons:
  apt:
    sources:
      - sourceline: 'ppa:dosemu2/ppa'
      - sourceline: 'ppa:stsp-0/djgpp'
    packages:
      - fdpp
      - comcom32
      - git
      - bash
      - autoconf
      - autotools-dev
      - automake
      - coreutils
      - linuxdoc-tools
      - bison
      - flex
      - gawk
      - sed
      - libx11-dev
      - libxext-dev
      - libslang2-dev
      - xfonts-utils
      - libgpm-dev
      - libasound2-dev
      - libsdl2-dev
      - libsdl1.2-dev
      - ladspa-sdk
      - libfluidsynth-dev
      - libao-dev
      - libvdeplug-dev
      - libreadline-dev
      - libjson-c-dev
      - binutils-dev
      - pkg-config
      - clang
      - nasm
      - libstdc++-5-dev
      - python3-pexpect
      - djgpp
      - qemu-kvm
    update: true

env: FDPP_KERNEL_DIR="$(pwd)/localfdpp/share/fdpp"

before_install:
  - echo "before_install"

install:
  - ./travis_build.sh

before_script:
  - sudo usermod -a -G kvm ${USER}

script:
  # launch the test this way to collect the new kvm group membership
  - sudo -E su ${USER} -c ./travis_test.sh
